packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@codemirror/lang-markdown": ^6.5.0
  "@headlessui/react": ^2.2.9
  "@heroicons/react": ^2.2.0
  "@milkdown/kit": ^7.21.2
  "@milkdown/react": ^7.21.2
  "@tailwindcss/vite": ^4.1.17
  "@tauri-apps/api": ^2.2.0
  "@tauri-apps/cli": ^2.2.1
  "@types/node": ^22.10.2
  "@types/react": ^19.0.1
  "@types/react-dom": ^19.0.2
  "@uiw/react-codemirror": ^4.25.10
  "@vitejs/plugin-react": ^4.3.4
  react: ^19.0.0
  react-dom: ^19.0.0
  tailwindcss: ^4.1.17
  typescript: ^5.7.2
  vite: ^6.0.3
  vitest: ^2.1.8

onlyBuiltDependencies:
  - esbuild
allowBuilds:
  esbuild: true
confirmModulesPurge: false
verifyDepsBeforeRun: false
